### PR TITLE
chore: Create dependabot.yml

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by dschmidt** [comment]
So if I read that correctly it should only update github actions?

Please be aware that we do not update the main branch but only the branch that backs https://github.com/owncloud/uppy/pull/1. So I guess dependabot should also target that branch?

... but we don't use github actions anyhow ...

FTR: Uppy 4.0 is about to be released very soon with basically all our changes merged. Only missing feature would be the WebDAV Import itself, but they promised to tackle that shortly after the release, so we can hopefully see it in 4.1.

So not sure we gain anything with this.

**Comment by DeepDiver1975** [comment]
> FTR: Uppy 4.0 is about to be released very soon with basically all our changes merged. Only missing feature would be the WebDAV Import itself, but they promised to tackle that shortly after the release, so we can hopefully see it in 4.1.

Seen this .... I just want to prepare everything in case it takes more time ....

**Comment by DeepDiver1975** [comment]
> So if I read that correctly it should only update github actions?

just a stupid dummy for now ....

**Comment by DeepDiver1975** [comment]
@dschmidt where can we chat?

**Comment by dschmidt** [comment]
talk.owncloud.com or oCIS Zoom

**Pull request merged**
